---
- hosts: openshift
  any_errors_fatal: true
  gather_facts: true
  roles:
  - role: common
    tags: [quotas, idling]
  - role: openshift-quotas
    tags: quotas
  - role: openshift-idling
    tags: idling